### ISSUE TITLE
yast2-gpmc will not run without `xset`

### ISSUE THREAD

**Issue by puellanivis** [yast/yast2-gpmc#17]
I use a minimal console-only install, and kept trying to use this, but it kept just immediately crashing/closing. Logs didn’t help, just said that it immediately quit after starting up. Eventually running `/usr/share/YaST2/clients/gpmc.py` directly got me this:
```
/usr/share/YaST2/clients# python3 gpmc.py
Traceback (most recent call last):
  File "gpmc.py", line 13, in <module>
    from wizards import GPMCSequence
  File "/usr/share/YaST2/include/gpmc/wizards.py", line 2, in <module>
    from dialogs import GPMC, GPME
  File "/usr/share/YaST2/include/gpmc/dialogs.py", line 23, in <module>
    have_advanced_gui = have_x()
  File "/usr/share/YaST2/include/gpmc/dialogs.py", line 21, in have_x
    p = Popen(['xset', '-q'], stdout=PIPE, stderr=PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'xset': 'xset'
```

After `zypper install xset` now it works. It’s probably enough to add `xset` to the requirements so that it automatically gets installed?

**Comment by dmulder** [comment]
Good catch. IIRC, I don't think that code is need anymore, so I might be able to simply remove this.

**Comment by dmulder** [comment]
Actually, that xset code was removed last Feb. Is there a reason you're using an old version?

**Comment by puellanivis** [comment]
🤷‍♀️ I’m using bog-standard openSUSE 15.1.
